Algoritmo "Exercico 4"

Var

NomeF: real
ValorF: inteiro
ValorV: inteiro


Inicio
escreval("Qual e o nome do funcionario? ")
leia(NomeF)

escreval("Qual e o Valor da Venda a ser Alcançado? ")
leia(ValorF)

escreval("Quantas vendas ele teve? ")
leia(ValorV)

se valorV > valorF entao
escreval("Parabéns! você ganhou o prêmio do mês! ")
senao
escreval("Que pena! Dessa vez você não conseguiu alcançar! ")
Fimalgoritmo
